hmcts/java-logging

build.gradle
gradle/wrapper/gradle-wrapper.properties
java-logging-dropwizard/build.gradle
java-logging-dropwizard/src/main/java/uk/gov/hmcts/reform/logging/dropwizard/bundles/LogbackConfigurationBundle.java
java-logging-httpcomponents/build.gradle
java-logging-spring/build.gradle

Add bintray gradle plugin

---

README.md

Rewrote section on adding `java-logging` module as a dependency, to split it into its two constituent components and list each dependency separately.

Updates for Version 1.2.1

---

.travis.yml

Notes:
- removed arbitrary markers containing request uri, time the response took. Giving this information in the message
- leaving request method and response code. I doubt method is needed
- adding date format
- adding log level spacing
- reducing namespace clog
- adding line number

Updating travis build

---

.travis.yml
build.gradle
java-logging-dropwizard/build.gradle
java-logging-dropwizard/src/main/java/uk/gov/hmcts/reform/logging/dropwizard/bundles/LogbackConfigurationBundle.java
java-logging-dropwizard/src/main/java/uk/gov/hmcts/reform/logging/dropwizard/exception/ConfigurationBundleException.java
java-logging-httpcomponents/build.gradle
java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptorTest.java
java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/TestAppender.java
java-logging-spring/build.gradle
java-logging-spring/src/test/java/uk/gov/hmcts/reform/logging/spring/RequestLoggingComponentTest.java
java-logging-spring/src/test/java/uk/gov/hmcts/reform/logging/spring/SpringBootTestApplication.java
java-logging-spring/src/test/resources/logback-test-receiver.xml
src/main/java/uk/gov/hmcts/reform/logging/filters/RequestIdsSettingFilter.java
src/main/java/uk/gov/hmcts/reform/logging/filters/RequestStatusLoggingFilter.java
src/main/resources/logback.xml
src/test/java/uk/gov/hmcts/reform/logging/PrettyPrintingDecoratorTest.java
src/test/java/uk/gov/hmcts/reform/logging/filters/RequestStatusLoggingFilterTest.java

This PR is a combination of 4 other PRs linked below in the list of notes. All reviewed and updated accordingly to comments and discussions in person
Highlights:
- adding date format
- adding log level spacing
- reducing namespace clog
- adding line number

RPE-16: coverage

---

src/main/java/uk/gov/hmcts/reform/logging/provider/AlertLevelJsonProvider.java
src/main/java/uk/gov/hmcts/reform/logging/provider/EventJsonProviders.java
src/main/resources/logback.xml
src/test/java/uk/gov/hmcts/reform/logging/provider/AlertLevelJsonProviderTest.java

Introducing alert level for json log. Pending clean-up work in the next PR. Non breaking for this implementation

RPE-16: custom json logging layout

---

java-logging-spring/src/test/java/uk/gov/hmcts/reform/logging/spring/SpringBootTestApplication.java
src/main/java/uk/gov/hmcts/reform/logging/exception/AbstractLoggingException.java
src/main/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayout.java
src/main/java/uk/gov/hmcts/reform/logging/provider/AlertLevelJsonProvider.java
src/main/resources/logback.xml
src/test/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayoutTest.java

As mentioned in #16 , here is the cleanup.
- not duplicating code in src
- deal with exception wrappers

Post RPE-16 cleanup

---

java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/FakeClock.java
java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptorTest.java
java-logging-spring/src/test/java/uk/gov/hmcts/reform/logging/spring/RequestLoggingComponentTest.java
src/main/java/uk/gov/hmcts/reform/logging/HttpHeaders.java
src/main/java/uk/gov/hmcts/reform/logging/MdcFields.java
src/main/java/uk/gov/hmcts/reform/logging/exception/AbstractLoggingException.java
src/main/java/uk/gov/hmcts/reform/logging/provider/AlertLevelJsonProvider.java
src/main/java/uk/gov/hmcts/reform/logging/provider/ErrorCodeJsonProvider.java
src/test/java/uk/gov/hmcts/reform/logging/AbstractLoggingTestSuite.java
src/test/java/uk/gov/hmcts/reform/logging/PrettyPrintingDecoratorTest.java
src/test/java/uk/gov/hmcts/reform/logging/filters/RequestStatusLoggingFilterTest.java
src/test/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayoutTest.java

Increasing levels of code quality in codacy configuration

Codacy issues

---

build.gradle
java-logging-httpcomponents/build.gradle
java-logging-httpcomponents/src/main/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestIdSettingInterceptor.java
java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestIdSettingInterceptorTest.java
src/main/java/uk/gov/hmcts/reform/logging/filters/RequestIdsSettingFilter.java
src/main/java/uk/gov/hmcts/reform/logging/tracing/RequestIdGenerator.java
src/test/java/uk/gov/hmcts/reform/logging/tracing/RequestIdGeneratorTest.java

https://tools.hmcts.net/jira/browse/ROC-1105
Generate request ID on outbound requests.

ROC-1105: Set request id on outbound request

---

build.gradle
src/main/java/uk/gov/hmcts/reform/logging/exception/AbstractLoggingException.java
src/main/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayout.java
src/main/java/uk/gov/hmcts/reform/logging/provider/AbstractRequireJsonProvider.java
src/test/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayoutTest.java

Custom layout did not print out stacktrace for console appender. Adding and testing

Print stacktrace for console appender

---

src/main/java/uk/gov/hmcts/reform/logging/exception/AbstractLoggingException.java
src/main/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayout.java
src/main/java/uk/gov/hmcts/reform/logging/provider/AbstractRequireJsonProvider.java
src/test/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayoutTest.java

The miss was introduced in #24 . Adding back the requirement

Compulsory exception in ERROR logs

---

README.md
build.gradle
java-logging-appinsights/README.md

Last commit I made was really a breaking change in hindsight so bumping version to 2.0.0

Updates version number to reflect the BC in the last commit

---

build.gradle

This is an improved version of #47

Upgrade logstash

---

README.md
gradle.properties
java-logging-appinsights/README.md
java-logging-appinsights/src/main/java/uk/gov/hmcts/reform/logging/appinsights/SyntheticHeaders.java
prepare-for-release.sh

Notes:
- include public access to headers
- better documentation of the synthetic initialiser

Update synthetic access

---

gradle.properties
java-logging-appinsights/build.gradle
java-logging-appinsights/src/main/java/uk/gov/hmcts/reform/logging/appinsights/AppInsightsRequestComponentConfiguration.java
java-logging-spring/build.gradle
java-logging-spring/src/main/java/uk/gov/hmcts/reform/logging/spring/RequestLoggingAutoConfiguration.java

https://tools.hmcts.net/jira/browse/ROC-3536
Updating to Spring Boot 2 / Spring Framework 5.

ROC-3636: Update to Spring Boot 2 / Spring Framework 5

---

README.md
gradle.properties
java-logging-appinsights/README.md
java-logging-appinsights/build.gradle
java-logging-spring/build.gradle

Fixes https://tools.hmcts.net/jira/browse/RDM-2464

Deps: Spring Boot to 2.0.3 for CVE-2018-1258

---

README.md
gradle.properties
java-logging-appinsights/README.md
src/main/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayout.java
src/test/java/uk/gov/hmcts/reform/logging/layout/ReformLoggingLayoutTest.java

Include the (missing) top-most exception information in error log

Include the top-most exception in error log

---

build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml
config/pmd/ruleset.xml
java-logging-appinsights/build.gradle
java-logging-appinsights/src/test/java/uk/gov/hmcts/reform/logging/appinsights/AppInsightsAllComponentsTest.java
java-logging-httpcomponents/src/main/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptor.java
java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/FakeClock.java
java-logging-httpcomponents/src/test/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptorTest.java
java-logging-spring/build.gradle
java-logging-spring/src/test/java/uk/gov/hmcts/reform/logging/spring/SpringBootTestApplication.java

Last commit actually suppresses what's unfixable. The rest is step-by-step dependency review/update. Note: PMD plugin update is most attention requiring change hence the biggest diff on it

Fix dependencies

---

build.gradle

Bumping checkstyle plugin to 8.18

Fix OWASP vulnerability

---

.dependabot/config.yml
gradle.properties
java-logging-appinsights/README.md
java-logging-appinsights/build.gradle

https://github.com/microsoft/ApplicationInsights-Java/blob/2.5.0-BETA/CHANGELOG.md

Upgrade appinsights

---

.travis.yml

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)
Notes:
*
*
*

move to openjdk

---

README.md

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)
Notes:
*
*
*

Add latest version badge

---

README.md
gradle.properties
java-logging-appinsights/README.md
java-logging-appinsights/build.gradle

1. Updated appinsights version to 2.5.1-BETA
2. Release 5.1.1-BETA

Upgraded appinsights version to 2.5.1-BETA

---

README.md
gradle.properties
java-logging-appinsights/README.md
java-logging-appinsights/build.gradle

Notes:
* Moving to latest AI Agent https://github.com/microsoft/ApplicationInsights-Java/releases/tag/2.5.1

Upgrading to Latest AI Agent

---

.github/workflows/gradle.yml
build.gradle

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)
Notes:
*add github action
*
*

add github action

---

java-logging-appinsights/src/main/resources/logback-appinsights.xml

revert  #216 
did not fix the app insight double logging and pod logs are missing

revert  #216

---

java-logging-appinsights/src/main/resources/logback-appinsights.xml

Using same ENV VAR as it is in main project so it aligns together.

Feature: allow overriding log level for App Insights

---

java-logging-appinsights/build.gradle

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)
Notes:
*
*
*

Bump app insights version

---

.github/workflows/gradle.yml
jitpack.yml

- Add custom install command for jitpack
- remove bintray upload step from workflow

Add custom install command for jitpack

---

README.md
build.gradle
gradle.properties
java-logging-appinsights/README.md
src/main/resources/reform-console-appender.xml

Existing one uses a third party lib which I don't think we need
Fixes https://github.com/hmcts/java-logging/issues/350

Use built-in async appender

---

.github/dependabot.yml

Remove dependabot.yml

---

.github/workflows/gradle.yml
README.md
build.gradle

Update to Java 17

---

README.md
gradle.properties
java-logging-appinsights/README.md

Release 6.1.0

---

README.md
gradle.properties
java-logging-appinsights/README.md
java-logging-appinsights/src/main/java/uk/gov/hmcts/reform/logging/appinsights/autoconfiguration/AppInsightsAutoConfiguration.java

Update heading tag in javadoc to use correct heading order

Update heading tag in javadoc to use correct heading order

---

jitpack.yml

Remove jitpack
